version: '2'

services:
    hdfs-name:
        image: quay.io/geodocker/hdfs:0.1
        command: name
        environment:
          HADOOP_MASTER_ADDRESS: hdfs-name
        ports:
          - 50070:50070
        volumes:
          # - './data/hdfs:/data/hdfs'
          - '/Volumes/Transcend/data/tmp/hdfs:/data/hdfs'
          - './data/source:/data/source'
    hdfs-data:
        image: quay.io/geodocker/hdfs:0.1
        command: data
        environment:
          HADOOP_MASTER_ADDRESS: hdfs-name
        depends_on:
          - hdfs-name
        volumes:
          - '/Volumes/Transcend/data/tmp/hdfs:/data/hdfs'
    zookeeper:
        image: quay.io/geodocker/zookeeper:latest
        ports:
          - 2181:2181
        #  volumes:
        #   - '/data/gt/hdfs:/data/hdfs'
    accumulo-master:
      image: quay.io/geodocker/accumulo:latest
      command: master --auto-init
      environment:
        HADOOP_MASTER_ADDRESS: hdfs-name
        ZOOKEEPERS: zookeeper
        ACCUMULO_PASSWORD: GisPwd
      depends_on:
        - zookeeper
    accumulo-monitor:
        image: quay.io/geodocker/accumulo:latest
        command: monitor
        environment:
          HADOOP_MASTER_ADDRESS: hdfs-name
          ZOOKEEPERS: zookeeper
        ports:
          - 50095:50095
        depends_on:
          - zookeeper
          - accumulo-master
    accumulo-tserver:
        image: quay.io/geodocker/accumulo:latest
        command: tserver
        environment:
          HADOOP_MASTER_ADDRESS: hdfs-name
          ZOOKEEPERS: zookeeper
        depends_on:
          - zookeeper
          - accumulo-master
    spark-master:
        image: quay.io/geodocker/spark:latest
        ports:
          - 4040:4040
          - 8080:8080
          - 8181:8181
        volumes:
          - './ingest:/ingest'
