version: '2'

services:

    hdfs-name:
        image: quay.io/geodocker/hdfs:0.1
        command: name
        environment:
          HADOOP_MASTER_ADDRESS: hdfs-name
        ports:
          - 50070:50070
        volumes:
          - '/Volumes/Transcend/data/tmp/hdfs:/data/hdfs'
          - './data/source:/data/source'

    hdfs-data:
        image: quay.io/geodocker/hdfs:0.1
        command: data
        environment:
          HADOOP_MASTER_ADDRESS: hdfs-name
        depends_on:
          - hdfs-name
        volumes:
          - '/Volumes/Transcend/data/tmp/hdfs:/data/hdfs'

    spark-master:
        image: quay.io/geodocker/spark:latest
        ports:
          - 4040:4040
          - 8080:8080
          - 8181:8181
        volumes:
          - './ingest:/ingest'
